name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_email: "${{ vars.HEROKU_EMAIL }}"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "bennun-rickys-folio"
          branch: "master"
          appdir: public
          buildpack: https://github.com/heroku/heroku-buildpack-php